module C.Union where

import C.System.Posix.Internals
import C.GHC.Base
import C.GHC.IO.Exception
import C.GHC.IO.Device
import C.GHC.Err
import C.GHC.MVar
import C.GHC.Natural
import C.GHC.List
import C.GHC.Exception
import C.GHC.Maybe
import C.GHC.Real
import C.GHC.IORef
import C.Data.Functor.Product
import C.Data.Functor.Utils
import C.Data.Functor.Const
import C.Data.Functor.Identity
import C.Data.Functor.Sum
import C.Data.Functor.Compose
import C.Data.Functor.Contravariant
import C.Data.STRef.Lazy
import C.Data.Traversable
import C.Data.Ord
import C.Data.Function
import C.Data.Monoid
import C.Data.Complex
import C.Data.Bifunctor
import C.Data.Bifoldable
import C.Data.List
import C.Data.Either
import C.Data.List.NonEmpty
import C.Data.Bitraversable
import C.Data.Semigroup.Internal
import C.Data.Tuple
import C.Data.Semigroup
import C.Data.Maybe
import C.Data.STRef
import C.Data.Eq
import C.Data.Functor
import C.Data.IORef
import C.Data.Bool
import C.Data.Foldable
import C.Foreign.C.String
import C.Control.Category
import C.Control.Applicative
import C.Control.Concurrent.QSemN
import C.Control.Concurrent.QSem
import C.Control.Concurrent.MVar
import C.Control.Monad.Fix
import C.Control.Monad.Zip
import C.Control.Monad.Fail
import C.Control.Monad.ST.Unsafe
import C.Control.Monad.ST.Imp
import C.Control.Monad.ST.Lazy
import C.Control.Monad.ST.Safe
import C.Control.Monad.ST.Lazy.Unsafe
import C.Control.Monad.ST.Lazy.Safe
import C.Control.Monad.ST.Strict
import C.Control.Monad.ST
import C.Control.Monad
import C.Control.Arrow

---------------------------
-- +++ INSTANCE DEFS +++ --
---------------------------

import InstAlternative
import InstAlternativeArrowMonada
import InstAlternativeComposefg
import InstAlternativeIO
import InstAlternativeKleislima
import InstAlternativeMaybe
import InstAlternativeOption
import InstAlternativeProductfg
import InstAlternativeWrappedArrowab
import InstAlternativeWrappedMonadm
import InstAlternativeZipList
import InstApplicative
import InstApplicativeArrowMonada
import InstApplicativeComplex
import InstApplicativeComposefg
import InstApplicativeConstm
import InstApplicativeDown
import InstApplicativeDual
import InstApplicativeEithere
import InstApplicativeFirst
import InstApplicativeIO
import InstApplicativeIdentity
import InstApplicativeKleislima
import InstApplicativeLast
import InstApplicativeMax
import InstApplicativeMaybe
import InstApplicativeMin
import InstApplicativeNonEmpty
import InstApplicativeOption
import InstApplicativeProduct
import InstApplicativeProductfg
import InstApplicativeStateLs
import InstApplicativeStateRs
import InstApplicativeSum
import InstApplicativeWrappedArrowab
import InstApplicativeWrappedMonadm
import InstApplicativeZipList
import InstApplicativea
import InstArrow
import InstArrowApply
import InstArrowApplyKleislim
import InstArrowChoice
import InstArrowChoiceKleislim
import InstArrowKleislim
import InstArrowLoop
import InstArrowLoopKleislim
import InstArrowPlusKleislim
import InstArrowZeroKleislim
import InstBifoldable
import InstBifoldableArg
import InstBifoldableConst
import InstBifoldableEither
import InstBifoldableK1i
import InstBifunctor
import InstBifunctorArg
import InstBifunctorConst
import InstBifunctorEither
import InstBifunctorK1i
import InstBitraversable
import InstBitraversableArg
import InstBitraversableConst
import InstBitraversableEither
import InstBitraversableK1i
import InstBoundedApfa
import InstCategory
import InstCategoryKleislim
import InstCategoryOp
import InstContravariantComparison
import InstContravariantComposefg
import InstContravariantConsta
import InstContravariantEquivalence
import InstContravariantK1ic
import InstContravariantOpa
import InstContravariantPredicate
import InstContravariantProductfg
import InstContravariantProxy
import InstContravariantSumfg
import InstContravariantU1
import InstContravariantV1
import InstContravariantfg
import InstEnumFirsta
import InstEnumLasta
import InstEnumMaxa
import InstEnumMina
import InstEnumRatioa
import InstEnumWrappedMonoida
import InstEq1Composefg
import InstEq1Productfg
import InstEq1Sumfg
import InstEqArgab
import InstEqComposefga
import InstEqIOException
import InstEqProductfga
import InstEqSumfga
import InstFailMonadFailSTs
import InstFloatingComplexa
import InstFloatingOpab
import InstFoldable
import InstFoldableAltf
import InstFoldableApf
import InstFoldableArga
import InstFoldableArrayi
import InstFoldableComposefg
import InstFoldableConstm
import InstFoldableDual
import InstFoldableEithera
import InstFoldableFirst
import InstFoldableIdentity
import InstFoldableLast
import InstFoldableMax
import InstFoldableMaybe
import InstFoldableMin
import InstFoldableNonEmpty
import InstFoldableOption
import InstFoldableProduct
import InstFoldableProductfg
import InstFoldableProxy
import InstFoldableSum
import InstFoldableSumfg
import InstFoldableU1
import InstFractionalComplexa
import InstFractionalOpab
import InstFractionalRatioa
import InstFunctor
import InstFunctorArga
import InstFunctorArrowMonada
import InstFunctorComposefg
import InstFunctorConstm
import InstFunctorDown
import InstFunctorDual
import InstFunctorEithera
import InstFunctorFirst
import InstFunctorIO
import InstFunctorIdentity
import InstFunctorKleislima
import InstFunctorLast
import InstFunctorMax
import InstFunctorMaybe
import InstFunctorMin
import InstFunctorNonEmpty
import InstFunctorOption
import InstFunctorProduct
import InstFunctorProductfg
import InstFunctorStateLs
import InstFunctorStateRs
import InstFunctorSum
import InstFunctorSumfg
import InstFunctorWrappedArrowab
import InstFunctorWrappedMonadm
import InstIntegralInteger
import InstIntegralNatural
import InstMonad
import InstMonadArrowMonada
import InstMonadComplex
import InstMonadDown
import InstMonadDual
import InstMonadEithere
import InstMonadFail
import InstMonadFailIO
import InstMonadFailMaybe
import InstMonadFirst
import InstMonadFix
import InstMonadFixAltf
import InstMonadFixApf
import InstMonadFixDown
import InstMonadFixDual
import InstMonadFixEithere
import InstMonadFixFirst
import InstMonadFixIO
import InstMonadFixIdentity
import InstMonadFixLast
import InstMonadFixMax
import InstMonadFixMaybe
import InstMonadFixMin
import InstMonadFixNonEmpty
import InstMonadFixOption
import InstMonadFixProduct
import InstMonadFixProductfg
import InstMonadFixSum
import InstMonadIO
import InstMonadIdentity
import InstMonadKleislima
import InstMonadLast
import InstMonadMax
import InstMonadMaybe
import InstMonadMin
import InstMonadNonEmpty
import InstMonadOption
import InstMonadPlusKleislima
import InstMonadPlusProductfg
import InstMonadProduct
import InstMonadProductfg
import InstMonadSum
import InstMonadZip
import InstMonadZipAltf
import InstMonadZipDown
import InstMonadZipDual
import InstMonadZipFirst
import InstMonadZipIdentity
import InstMonadZipLast
import InstMonadZipM1icf
import InstMonadZipMaybe
import InstMonadZipNENonEmpty
import InstMonadZipPar1
import InstMonadZipProduct
import InstMonadZipProductfg
import InstMonadZipProxy
import InstMonadZipRec1f
import InstMonadZipSum
import InstMonadZipU1
import InstMonadZipfg
import InstMonada
import InstMonoid
import InstMonoidAll
import InstMonoidAltfa
import InstMonoidAny
import InstMonoidApfa
import InstMonoidDuala
import InstMonoidEndoa
import InstMonoidEquivalencea
import InstMonoidFirsta
import InstMonoidIOa
import InstMonoidLasta
import InstMonoidMaxa
import InstMonoidMaybea
import InstMonoidMina
import InstMonoidOptiona
import InstMonoidOrdering
import InstMonoidPredicatea
import InstMonoidProducta
import InstMonoidSuma
import InstMonoidWrappedMonoidm
import InstMonoida
import InstMonoidab
import InstMonoidabc
import InstMonoidabcd
import InstMonoidabcde